### ISSUE TITLE
Model Editing Source Code

### ISSUE THREAD

**Issue by asdfo123** [domenicrosati/longform-evaluation-model-editing#1]
Thanks for your great work to the community!

How do you perform the various model editing methods mentioned in the paper? Could you please provide the source code？

**Comment by domenicrosati** [comment]
Oh it was just with EasyEdit - It is best to use EasyEdit directly but feel free to reach out to me directly by email if you have issues as I can share our implementation.

**Comment by asdfo123** [comment]
> Oh it was just with EasyEdit - It is best to use EasyEdit directly but feel free to reach out to me directly by email if you have issues as I can share our implementation.

OK, I got it! Thanks again for your reply.
